GetHTML.py, 33, (<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.po.st%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3571e8fe48>: Failed to establish a new connection: [Errno -2] Name or service not known',))",),), <traceback object at 0x7f3571ea6fc8>)
